config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'home#index'
  resources :boats
  resources :jobs
  root to: 'home#index'
  # get '/boats/:id/jobs' => 'boats#jobs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
  has_and_belongs_to_many :jobs
  validates_presence_of :name, :container_capacity, :location
  validates :name, uniqueness: true
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/models/boats_job.rb
class BoatsJob < ApplicationRecord
  belongs_to :boat
  belongs_to :job
end

app/models/job.rb
class Job < ApplicationRecord
  has_and_belongs_to_many :boats
  validates_presence_of :description, :origin, :destination, :cost, :containers_needed
  validates_numericality_of :cost, :greater_than_or_equal_to => 1000
  validates :description, length: {minimum: 50}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  def index
    @boats = Boat.all
    @jobs = Job.all
  end

  def show
    @boat = Boat.find(params[:id])
    @jobs = Job.all
  end

  def new
    @boat = Boat.new
    @jobs = Job.all
  end

  def create
    @boat = Boat.new(boat_params)
    if @boat.save
      flash[:notice] = "Successfully registered boat"
      redirect_to boat_path(@boat)
    else
      flash[:alert] = "There was an issue registering boat"
      render :new
    end
  end

  def edit
    @boat = Boat.find(params[:id])
    @jobs = Job.all
  end

  def update
    @boat = Boat.find(params[:id])
    @boat.update(boat_params)
    if @boat.save
      respond_to do |format|
        format.js
        format.html
      end
      flash[:notice] = "Boat updated successfully"
      redirect_to boat_path(@boat)
    else
      flash[:alert] = "There was an issue updating boat"
      render :edit
    end
  end

  # def jobs
  #   @boat = Boat.find(params[:id])
  #   @jobs = Job.all
  # end

  private

  def boat_params
    params.require(:boat).permit(:name, :container_capacity, :location, :photo, {job_ids: []})
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      flash[:notice] = "Job registered successfully"
      redirect_to job_path(@job)
    else
      flash[:alert] = "There was an issue registering job"
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    @job.update(job_params)
    if @job.save
      respond_to do |format|
        format.js
        format.html
      end
      flash[:notice] = "Job updated successfully"
      redirect_to job_path(@job)
    else
      flash[:alert] = "There was an issue updating job"
      render :edit
    end
  end

  private

  def job_params
    params.require(:job).permit(:description, :origin, :destination, :cost, :containers_needed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boat_helper.rb
module BoatHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_helper.rb
module JobHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/boats/_boat_form.html.erb
<%= form_for @boat, :html => {:multipart => true} do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br>
<%= f.label :container_capacity %>
<%= f.number_field :container_capacity %><br>
<%= f.label :location %>
<%= f.select :location, ['Alberta', 'California', 'Florida', 'New York', 'Seoul', 'Texas', 'Tokyo', 'Vancouver'] %><br>
<%= f.file_field :photo %><br>
<%= f.collection_check_boxes(:job_ids, Job.all, :id, :description) do |b| %>
  <%= b.label class:'label-checkbox' do %>
  <%= b.check_box + b.text%>
  <% end %>
<% end %>
<%= f.submit %>
<% end %>

app/views/boats/edit.html.erb
<% if @boat.errors.full_messages.any? %>
<ul>
  <% @boat.errors.full_messages.each do |error_message| %>
  <li><%= error_message %></li> <br />
  <% end %>
</ul>
<% end %>

<%= form_for @boat, :html => {:multipart => true}, remote:true do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br>
<%= f.label :container_capacity %>
<%= f.number_field :container_capacity %><br>
<%= f.label :location %>
<%= f.select :location, ['Alberta', 'California', 'Florida', 'New York', 'Seoul', 'Texas', 'Tokyo', 'Vancouver'] %><br>
<%= f.file_field :photo %><br>
<%= f.collection_check_boxes(:job_ids, Job.all, :id, :description) do |b| %>
  <%= b.label class:'label-checkbox' do %>
  <%= b.check_box + b.text%>
  <% end %>
<% end %>
<%= f.submit %>
<% end %>

app/views/boats/index.html.erb
<div id='boats_index'>
<h1>Boats</h1>

<%= link_to "New Ship", new_boat_path %>

<table>
  <tr>
    <th>Ship Name</th>
    <th>Container Capacity</th>
    <th>Location</th>
  </tr>
<% @boats.each do |boat| %>
<tr>
  <td>
    <%=link_to boat.name, boat_path(boat) %> </li>
  </td>
  <td><%=boat.container_capacity%></td>
  <td><%=boat.location%></td>
</tr>
<%end%>
</table>
</div>

app/views/boats/new.html.erb
<h1>Boats new</h1>

<% if @boat.errors.full_messages.any? %>
<ul>
  <% @boat.errors.full_messages.each do |error_message| %>
  <li><%= error_message %></li> <br />
  <% end %>
</ul>
<% end %>

<%= render "boat_form" %>

app/views/boats/show.html.erb
<h1>Boat show</h1>
<%= image_tag @boat.photo.url(:medium) %>
<h3>Name</h3>
<p><%=@boat.name%></p>
<h3>Container Capacity</h3>
<p><%=@boat.container_capacity%></p>
<h3>Location</h3>
<p><%=@boat.location%></p>
<%= link_to "Edit", edit_boat_path(@boat) %>
<br>

<h3>Jobs</h3>
<% @boat.jobs.each do |job| %>
<%= link_to job.description, job_path(job) %><br>
<% end %>

app/views/home/index.html.erb
<div id='home_div'>
<%= image_tag('home.jpg', id:'home_img') %>
</div>

app/views/jobs/_job_form.html.erb
<%= form_for @job do |f| %>
<%= f.label :description %>
<%= f.text_area :description %>
<%= f.label :origin %>
<%= f.select :origin, ['Alberta', 'California', 'Florida', 'New York', 'Seoul', 'Texas' 'Tokyo', 'Vancouver'] %>
<%= f.label :destination %>
<%= f.select :destination, ['Alberta', 'California', 'Florida', 'New York', 'Seoul', 'Texas', 'Tokyo', 'Vancouver'] %>
<%= f.label :cost %>
<%= f.text_field :cost %>
<%= f.label :containers_needed %>
<%= f.number_field :containers_needed %>
<%= f.submit %>
<% end %>

app/views/jobs/edit.html.erb
<% if @job.errors.full_messages.any? %>
<ul>
  <% @job.errors.full_messages.each do |error_message| %>
  <li><%= error_message %></li> <br />
  <% end %>
</ul>
<% end %>

<%= form_for @job, remote:true do |f| %>
<%= f.label :description %>
<%= f.text_area :description %>
<%= f.label :origin %>
<%= f.select :origin, ['Alberta', 'California', 'Florida', 'New York', 'Seoul', 'Texas' 'Tokyo', 'Vancouver'] %>
<%= f.label :destination %>
<%= f.select :destination, ['Alberta', 'California', 'Florida', 'New York', 'Seoul', 'Texas', 'Tokyo', 'Vancouver'] %>
<%= f.label :cost %>
<%= f.text_field :cost %>
<%= f.label :containers_needed %>
<%= f.number_field :containers_needed %>
<%= f.submit %>
<% end %>

app/views/jobs/index.html.erb
<h1>Jobs</h1>

<%= link_to "New Job", new_job_path %>
<table border="1" cellpadding="10">
  <tr>
    <th>Description</th>
    <th>Origin</th>
    <th>Destination</th>
  </tr>
<% @jobs.each do |job| %>
<tr>
  <td>
    <%=link_to job.description, job_path(job) %> </li>
  </td>
  <td><%=job.origin%></td>
  <td><%=job.destination%></td>
</tr>
<%end%>
</table>

app/views/jobs/new.html.erb
<% if @job.errors.full_messages.any? %>
<ul>
  <% @job.errors.full_messages.each do |error_message| %>
  <li><%= error_message %></li> <br />
  <% end %>
</ul>
<% end %>

<%= render "job_form" %>

app/views/jobs/show.html.erb
<!-- t.string   "description"
t.string   "origin"
t.string   "destination"
t.decimal  "cost"
t.integer  "containers_needed" -->

<h1>Job show</h1>

<h3>Description</h3>
<p><%=@job.description%></p>
<h3>Origin</h3>
<p><%=@job.origin%></p>
<h3>Destination</h3>
<p><%=@job.destination%></p>
<h3>Cost</h3>
<p><%=@job.cost%></p>
<h3>Containers Needed</h3>
<p><%=@job.containers_needed%></p>

<%= link_to "Edit", edit_job_path(@job) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shipped</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://unpkg.com/sakura.css/css/sakura.css" type="text/css"> -->
</head>

<body>
  <nav>
    <%= link_to "Home", root_path %>
    <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <%= link_to "Account", edit_user_registration_path %>
    <%= link_to "Jobs", jobs_path %>
    <%= link_to "Ships", boats_path %>
    <% else %>
    <%= link_to "Sign In", user_session_path %>
    <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
  </nav>
  <% if flash[:notice] %>
  <div id="notice"><%= flash[:notice] %></div>
  <% elsif flash[:alert] %>
  <div id="alert"><%= flash[:alert] %></div>
  <% end %>

  <div class='main'>
  <%= yield %>
  </div>
</body>
</html>